services:
  - type: web
    name: restaurant-app
    env: docker
    plan: free
    region: frankfurt

    dockerfilePath: ./Dockerfile
    context: .

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://restaurant-app.onrender.com

      # --- Database (Aiven MySQL) ---
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-1d7f8934-yaredmengiste01-a3a7.j.aivencloud.com
      - key: DB_PORT
        value: "11849"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false # Set the Aiven password in Render Dashboard

      # --- Google Socialite ---
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://restaurant-app.onrender.com/auth/google-callback

      # --- App Keys & Drivers ---
      - key: APP_KEY
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: public

    disk:
      name: restaurant-storage
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
